name: Build docker image and publish to Quay.io and GAR

on:
  release:
    types:
      - published

jobs:
  push-to-quay-and-gcr:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    env:
      TAG: ${{ github.ref_name }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Log in to quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: 'open-targets-eu-dev'
          workload_identity_provider: projects/426265110888/locations/global/workloadIdentityPools/github/providers/my-repo

      - name: 'Print authenticated user'
        run: 'gcloud auth list'

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            quay.io/opentargets/platform-input-support-test:latest
            quay.io/opentargets/platform-input-support-test:${{ github.ref_name }}
            europe-west1-docker.pkg.dev/open-targets-eu-dev/platform-input-support-test/platform-input-support-test:latest
            europe-west1-docker.pkg.dev/open-targets-eu-dev/platform-input-support-test/platform-input-support-test:${{ github.ref_name }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: quay.io/opentargets/platform-input-support-test
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
